name: 执行接口自动化

# 监控：接收 Webhook 通知（业务代码仓库）
on:
  # workflow 只能监听同仓库下的事件
  #workflow_run:
  #  workflows:
  #    - push              
  #    - pull_request       
  #    - deployment         
  #    - deployment_status 
  #    - release            
  #  types: [completed]
  #  branches: [main]

      # ==============================================
      # 这里是接收开发仓库action的通知
      # ==============================================
  # 这里是接收这5种事件的全部类型    
  #repository_dispatch:
  #  types:
  #    - deployment
  #    - deployment_status
  #    - push
  #    - pull_request
  #    - release

  # 只保留需要的类型
  repository_dispatch:
    types:
      - push
      - pull_request_opened
      - pull_request_synchronize
      - release
      - deployment_status_test_success
      - deployment_status_test_failure
      - deployment_status_uat_success
      - deployment_status_main_success
      - deployment_status_master_success
      # 如果你还有其他环境（如 develop），请按需添加   

      # ==============================================
      # 这里是测试代码 push 到测试代码仓库
      # ==============================================      
  push:
    branches: [ main, master, test, uat ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:      
      # 拉取自己仓库里的 postman 脚本
      - uses: actions/checkout@v4  
      
      # ==============================================
      # 这里会自动获取传过来的 事件类型、分支
      # ==============================================
      - name: 接收开发仓库事件
        run: |
          echo "触发事件：${{ github.event.client_payload.event_name }}"
          echo "测试提交：${{ github.event.client_payload.sha }}"
          
          echo "========= 收到通知 ========="
          echo "事件类型（action）: ${{ github.event.action }}"
          echo "Client Payload: ${{ toJSON(github.event.client_payload) }}"
          echo "目标分支: ${{ github.event.client_payload.ref }}"
          echo "部署环境: ${{ github.event.client_payload.environment }}"
          echo "部署状态: ${{ github.event.client_payload.deployment_status }}"
          echo "PR 动作: ${{ github.event.client_payload.pr_action }}"


      # 安装 Node
      - name: 安装Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 安装 Newman
      - name: 安装 Newman
        run: |
          npm install -g newman newman-reporter-html
          

      # ==============================================
      # 执行你的 Postman 脚本（你原来的命令不变）
      # ==============================================
      - name: 运行xxx模块接口测试
        run: |
          newman run collections/test_for_auto.postman_collection.json \
          -e environments/测试环境.postman_environment.json \
          -r html \
          --reporter-html-export reports/user-api-report.html
          

      # ==========================
      # 自动发邮件（163邮箱）
      # ==========================
      - name: 发送测试报告到邮箱
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MY_EMAIL }}
          password: ${{ secrets.EMAIL_PWD }}
          subject: "✅ 接口自动化测试完成 - GitHub Actions"
          body: "测试已完成，附件为 HTML 测试报告，请查收。"
          to: "xiao_bai828@163.com"
          from: "接口自动化测试机器人"
          attachments: reports/*.html
