name: Postman接口自动化测试 + 邮件报告
on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装 Newman
        run: |
          npm install -g newman newman-reporter-html
          
      - name: 运行xxx模块的接口测试
        run: |
          newman run collections/test_for_auto.postman_collection.json \
          -e environments/测试环境.postman_environment.json \
          -r html \
          --reporter-html-export reports/user-api-report.html
          

      # ==========================
      # 自动发邮件（163邮箱）
      # ==========================
      - name: 发送测试报告到邮箱
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MY_EMAIL }}
          password: ${{ secrets.EMAIL_PWD }}
          subject: "✅ 接口自动化测试完成 - GitHub Actions"
          body: "测试已完成，附件为 HTML 测试报告，请查收。"
          to: "xiao_bai828@163.com"
          from: "接口自动化测试机器人"
          attachments: reports/*.html